Document: libfacet
Title: Debian libfacet Manual
Author: <insert document author here>
Abstract: This manual describes what libfacet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfacet/libfacet.sgml.gz

Format: postscript
Files: /usr/share/doc/libfacet/libfacet.ps.gz

Format: text
Files: /usr/share/doc/libfacet/libfacet.text.gz

Format: HTML
Index: /usr/share/doc/libfacet/html/index.html
Files: /usr/share/doc/libfacet/html/*.html
